### ISSUE TITLE
Como nos ponemos en contacto para la practica¿?

### ISSUE THREAD

**Issue by 1425774** [hadzak3/boat_sink_tqs#1]
Buenas, no sabia como contactar y por eso abro esto. Mi correo es jacob.folch@e-campus.uab.cat y más que nada es para acordar una fecha para la RFT, para hacerla el siguiente finde o la semana que viene.

Gracias!

**Comment by hadzak3** [comment]
Buenos días,

¿El martes 8 de diciembre a las 10h os va bien?

Enviadnos vuestros usuarios de Discord, por favor.

Saludos,
Zaka.

Missatge de 1425774 <notifications@github.com> del dia dt., 1 de des. 2020
a les 8:58:

**Comment by hadzak3** [comment]
Por cierto, mi mail es zakaria.elhaddad@e-campus.uab.cat
